# Generated by Django 5.2.8 on 2025-11-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufloria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_text', models.TextField(default='\nNew Order:\nStudent: {student}\nPerfume: {perfume}\nQty: {qty} ml\nPrice: ₹{price}\n')),
            ],
        ),
    ]
