# Generated by Django 5.2.8 on 2025-12-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufloria', '0002_whatsapptemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='template_text',
            field=models.TextField(default='\n✨ *New Order Request* ✨\n───────────────\n👤 Student: *{student}*\n🌺 Perfume: *{perfume}*\n📦 Qty: *{qty} ml*\n💵 Price: *₹{price}*\n───────────────\n> Please confirm to proceed.\n'),
        ),
    ]
